export const ROLES = {
  ADMIN: 'ADMIN',
  ARTIST: 'ARTIST',
  PROGRAMMER: 'PROGRAMMER',
  MANAGER: 'MANAGER',
  ANALYST: 'ANALYST',
  TESTER: 'TESTER'
};

export const ALL_PERMISSIONS = {
  MANAGE_USERS: 'manage_users',
  CREATE_PROJECTS: 'create_projects',
  DELETE_MODELS: 'delete_models',
  UPLOAD_MODELS: 'upload_models',
  EDIT_MODELS: 'edit_models',
  EDIT_MODEL_DESCRIPTION: 'edit_model_description', // Устаревшее, входит в EDIT_MODELS, оставлено для обратной совместимости
  EDIT_MODEL_SPHERE: 'edit_model_sphere',
  EDIT_MODEL_SCREENSHOTS: 'edit_model_screenshots', // Устаревшее, входит в EDIT_MODELS, оставлено для обратной совместимости
  EDIT_ALL_MODELS: 'edit_all_models', // Кастомное право для редактирования всех моделей (для Художника)
  DOWNLOAD_MODELS: 'download_models',
  EDIT_PROJECTS: 'edit_projects',
  ADD_SPHERE: 'add_sphere',
  EDIT_SPHERE: 'edit_sphere' // Редактирование сфер
};

export const PERMISSION_LABELS = {
  [ALL_PERMISSIONS.MANAGE_USERS]: 'Управление пользователями',
  [ALL_PERMISSIONS.CREATE_PROJECTS]: 'Создание проектов',
  [ALL_PERMISSIONS.DELETE_MODELS]: 'Удаление моделей (по запросу)',
  [ALL_PERMISSIONS.UPLOAD_MODELS]: 'Загрузка моделей',
  [ALL_PERMISSIONS.EDIT_MODELS]: 'Редактирование моделей',
  [ALL_PERMISSIONS.EDIT_MODEL_DESCRIPTION]: 'Редактирование описания (устаревшее)',
  [ALL_PERMISSIONS.EDIT_MODEL_SPHERE]: 'Редактирование сферы модели',
  [ALL_PERMISSIONS.EDIT_MODEL_SCREENSHOTS]: 'Редактирование скриншотов (устаревшее)',
  [ALL_PERMISSIONS.EDIT_ALL_MODELS]: 'Редактирование всех моделей',
  [ALL_PERMISSIONS.DOWNLOAD_MODELS]: 'Скачивание моделей',
  [ALL_PERMISSIONS.EDIT_PROJECTS]: 'Редактирование проектов',
  [ALL_PERMISSIONS.ADD_SPHERE]: 'Создание сферы',
  [ALL_PERMISSIONS.EDIT_SPHERE]: 'Редактирование сферы'
}

export const ROLE_OPTIONS = [
  { value: 'ARTIST', label: 'Художник' },
  { value: 'PROGRAMMER', label: 'Программист' },
  { value: 'MANAGER', label: 'Менеджер' },
  { value: 'ANALYST', label: 'Аналитик' },
  { value: 'TESTER', label: 'Тестировщик' }
];


export const DEFAULT_PERMISSIONS = {
  [ROLES.ADMIN]: [
    ALL_PERMISSIONS.MANAGE_USERS,
    ALL_PERMISSIONS.CREATE_PROJECTS,
    ALL_PERMISSIONS.DELETE_MODELS,
    ALL_PERMISSIONS.UPLOAD_MODELS,
    ALL_PERMISSIONS.EDIT_MODELS,
    ALL_PERMISSIONS.DOWNLOAD_MODELS,
    ALL_PERMISSIONS.EDIT_PROJECTS,
    ALL_PERMISSIONS.ADD_SPHERE,
    ALL_PERMISSIONS.EDIT_SPHERE
  ],
  [ROLES.ARTIST]: [
    ALL_PERMISSIONS.UPLOAD_MODELS,
    ALL_PERMISSIONS.EDIT_MODELS,
    ALL_PERMISSIONS.EDIT_MODEL_SPHERE,
    ALL_PERMISSIONS.DOWNLOAD_MODELS,
    ALL_PERMISSIONS.DELETE_MODELS,
    ALL_PERMISSIONS.ADD_SPHERE,
    ALL_PERMISSIONS.EDIT_SPHERE
  ],
  [ROLES.PROGRAMMER]: [
    ALL_PERMISSIONS.DOWNLOAD_MODELS,
    ALL_PERMISSIONS.DELETE_MODELS
  ],
  [ROLES.MANAGER]: [
    ALL_PERMISSIONS.EDIT_MODELS,
    ALL_PERMISSIONS.EDIT_MODEL_SPHERE,
    ALL_PERMISSIONS.DOWNLOAD_MODELS,
    ALL_PERMISSIONS.UPLOAD_MODELS,
    ALL_PERMISSIONS.CREATE_PROJECTS,
    ALL_PERMISSIONS.EDIT_PROJECTS,
    ALL_PERMISSIONS.DELETE_MODELS,
    ALL_PERMISSIONS.ADD_SPHERE,
    ALL_PERMISSIONS.EDIT_SPHERE
  ],
  [ROLES.ANALYST]: [
    ALL_PERMISSIONS.EDIT_MODELS,
    ALL_PERMISSIONS.EDIT_MODEL_SPHERE,
    ALL_PERMISSIONS.DOWNLOAD_MODELS,
    ALL_PERMISSIONS.UPLOAD_MODELS,
    ALL_PERMISSIONS.CREATE_PROJECTS,
    ALL_PERMISSIONS.EDIT_PROJECTS,
    ALL_PERMISSIONS.DELETE_MODELS,
    ALL_PERMISSIONS.ADD_SPHERE,
    ALL_PERMISSIONS.EDIT_SPHERE
  ],
  [ROLES.TESTER]: [
    ALL_PERMISSIONS.DOWNLOAD_MODELS,
    ALL_PERMISSIONS.DELETE_MODELS
  ]
};