export const ROLES = {
  ADMIN: 'ADMIN',
  ARTIST: 'ARTIST',
  PROGRAMMER: 'PROGRAMMER',
  MANAGER: 'MANAGER',
  ANALYST: 'ANALYST'
};

export const ALL_PERMISSIONS = {
  MANAGE_USERS: 'manage_users',
  CREATE_PROJECTS: 'create_projects',
  DELETE_MODELS: 'delete_models',
  UPLOAD_MODELS: 'upload_models',
  EDIT_MODELS: 'edit_models',
  EDIT_MODEL_DESCRIPTION: 'edit_model_description',
  EDIT_MODEL_SPHERE: 'edit_model_sphere',
  EDIT_MODEL_SCREENSHOTS: 'edit_model_screenshots',
  DOWNLOAD_MODELS: 'download_models',
  EDIT_PROJECTS: 'edit_projects'
};

export const PERMISSION_LABELS = {
  [ALL_PERMISSIONS.MANAGE_USERS]: 'Управление пользователями',
  [ALL_PERMISSIONS.CREATE_PROJECTS]: 'Создание проектов',
  [ALL_PERMISSIONS.DELETE_MODELS]: 'Удаление моделей',
  [ALL_PERMISSIONS.UPLOAD_MODELS]: 'Загрузка моделей',
  [ALL_PERMISSIONS.EDIT_MODELS]: 'Редактирование моделей',
  [ALL_PERMISSIONS.EDIT_MODEL_DESCRIPTION]: 'Редактирование описания',
  [ALL_PERMISSIONS.EDIT_MODEL_SPHERE]: 'Редактирование сферы',
  [ALL_PERMISSIONS.EDIT_MODEL_SCREENSHOTS]: 'Редактирование скриншотов',
  [ALL_PERMISSIONS.DOWNLOAD_MODELS]: 'Скачивание моделей',
  [ALL_PERMISSIONS.EDIT_PROJECTS]: 'Редактирование проектов'
}

export const ROLE_OPTIONS = [
  { value: 'ARTIST', label: 'Художник' },
  { value: 'PROGRAMMER', label: 'Программист' },
  { value: 'MANAGER', label: 'Менеджер' },
  { value: 'ANALYST', label: 'Аналитик' }
];


export const DEFAULT_PERMISSIONS = {
  [ROLES.ADMIN]: [
    ALL_PERMISSIONS.MANAGE_USERS,
    ALL_PERMISSIONS.CREATE_PROJECTS,
    ALL_PERMISSIONS.DELETE_MODELS,
    ALL_PERMISSIONS.UPLOAD_MODELS,
    ALL_PERMISSIONS.EDIT_MODELS,
    ALL_PERMISSIONS.DOWNLOAD_MODELS,
    ALL_PERMISSIONS.EDIT_PROJECTS
  ],
  [ROLES.ARTIST]: [
    ALL_PERMISSIONS.UPLOAD_MODELS,
    ALL_PERMISSIONS.EDIT_MODELS,
    ALL_PERMISSIONS.EDIT_MODEL_DESCRIPTION,
    ALL_PERMISSIONS.EDIT_MODEL_SPHERE,
    ALL_PERMISSIONS.EDIT_MODEL_SCREENSHOTS,
    ALL_PERMISSIONS.DOWNLOAD_MODELS,
    ALL_PERMISSIONS.DELETE_MODELS
  ],
  [ROLES.PROGRAMMER]: [
    ALL_PERMISSIONS.DOWNLOAD_MODELS
  ],
  [ROLES.MANAGER]: [
    ALL_PERMISSIONS.EDIT_MODEL_DESCRIPTION,
    ALL_PERMISSIONS.EDIT_MODEL_SPHERE,
    ALL_PERMISSIONS.EDIT_MODEL_SCREENSHOTS,
    ALL_PERMISSIONS.DOWNLOAD_MODELS,
    ALL_PERMISSIONS.CREATE_PROJECTS,
    ALL_PERMISSIONS.EDIT_PROJECTS
  ],
  [ROLES.ANALYST]: [
    ALL_PERMISSIONS.EDIT_MODEL_DESCRIPTION,
    ALL_PERMISSIONS.EDIT_MODEL_SPHERE,
    ALL_PERMISSIONS.EDIT_MODEL_SCREENSHOTS,
    ALL_PERMISSIONS.DOWNLOAD_MODELS,
    ALL_PERMISSIONS.CREATE_PROJECTS,
    ALL_PERMISSIONS.EDIT_PROJECTS,
    ALL_PERMISSIONS.DELETE_MODELS
  ]
};