import "./styles/globals.css";

export const metadata = {
  title: "Библиотека 3D-моделей",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="ru" className="h-full">
      <body className="antialiased h-full">
        {children}
      </body>
    </html>
  );
}