import { Geist, Geist_Mono } from "next/font/google";
import "./styles/globals.css";
import ErrorBoundaryWrapper from "@/components/ErrorBoundaryWrapper";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Библиотека 3D-моделей",
  description: "Generated by create next app",
  icons: {
    icon: '/Logoico 1.svg',
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="ru" className="h-full">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased h-full`}>
        <ErrorBoundaryWrapper>
          {children}
        </ErrorBoundaryWrapper>
      </body>
    </html>
  );
}